export interface Movie {
  id: number;
  title: string;
  slug: string;
  description: string;
  image: string;
  backdropUrl?: string;
  trailerUrl?: string;
  videoUrl?: string;
  year: number;
  duration: string;
  rating: number;
  genres: string[];
  languages: string[];
  quality: string;
  pgRating: string;
  label?: string;
  subtitle?: string;
  releaseDate?: string;
  isFeatured?: boolean;
  isUpcoming?: boolean;
  isTrending?: boolean;
}

export const FEATURED_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Oppenheimer",
    slug: "oppenheimer",
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    image: "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
    year: 2023,
    duration: "3h 0m",
    rating: 8.9,
    genres: ["Biography", "Drama", "History"],
    languages: ["English", "German", "Dutch"],
    quality: "IMAX / 4K",
    pgRating: "R",
    label: "Universal Pictures",
    subtitle: "The World Forever Changes",
    releaseDate: "21/07/2023",
  },
  {
    id: 2,
    title: "Dune: Part Two",
    slug: "dune-part-two",
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    image: "https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520b4q.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    year: 2024,
    duration: "2h 46m",
    rating: 8.6,
    genres: ["Sci-Fi", "Adventure", "Action"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    label: "Warner Bros. Pictures",
    subtitle: "Long Live the Fighters",
    releaseDate: "01/03/2024",
  },
  {
    id: 3,
    title: "Spider-Man: Across the Spider-Verse",
    slug: "spider-man-across-the-spider-verse",
    description:
      "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    image: "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    year: 2023,
    duration: "2h 20m",
    rating: 8.7,
    genres: ["Animation", "Action", "Adventure"],
    languages: ["English", "Spanish"],
    quality: "HD / 4K",
    pgRating: "PG",
    label: "Sony Pictures Animation",
    subtitle: "It's How You Wear the Mask",
    releaseDate: "02/06/2023",
  },
  {
    id: 4,
    title: "Interstellar",
    slug: "interstellar",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival on distant worlds.",
    image: "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rAiYTsqOdAc0VAlxAqAe0qZ9nuk.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    year: 2014,
    duration: "2h 49m",
    rating: 8.7,
    genres: ["Sci-Fi", "Drama", "Adventure"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    label: "Paramount Pictures",
    subtitle: "Mankind Was Born on Earth. It Was Never Meant to Die Here.",
    releaseDate: "07/11/2014",
  },
  {
    id: 5,
    title: "The Dark Knight",
    slug: "the-dark-knight",
    description:
      "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent, until the Joker unleashes total chaos.",
    image: "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    year: 2008,
    duration: "2h 32m",
    rating: 9.0,
    genres: ["Action", "Crime", "Drama"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    label: "Warner Bros.",
    subtitle: "Why So Serious?",
    releaseDate: "18/07/2008",
  },
  {
    id: 6,
    title: "Deadpool & Wolverine",
    slug: "deadpool-and-wolverine",
    description:
      "Wade Wilson's civilian life is interrupted when the Time Variance Authority recruits him for a high-stakes multiverse mission with Wolverine.",
    image: "https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=73_1biulkYk",
    year: 2024,
    duration: "2h 8m",
    rating: 7.7,
    genres: ["Action", "Comedy", "Sci-Fi"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "R",
    label: "Marvel Studios",
    subtitle: "Everyone Deserves a Happy Ending",
    releaseDate: "26/07/2024",
  },
];

export const UPCOMING_MOVIES: Movie[] = [
  {
    id: 1,
    title: "AVENGERS: DOOMSDAY",
    slug: "avengers-doomsday",
    label: "Marvel Studios",
    subtitle: "The Multiverse Collapses",
    description:
      "A new era of the MCU begins as Doctor Doom rises to reshape reality. The remaining heroes must unite for the ultimate stand against cosmic destruction.",
    image: "https://image.tmdb.org/t/p/w780/mQZxtvA6p2dE79D0fR0iYIq57Qe.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    releaseDate: "01/05/2026",
    year: 2026,
    duration: "2h 45m",
    rating: 0.0,
    genres: ["Action", "Sci-Fi", "Adventure"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isUpcoming: true,
  },
  {
    id: 2,
    title: "THE BATMAN PART II",
    slug: "the-batman-part-ii",
    label: "DC Studios",
    subtitle: "Deep in the Shadows",
    description:
      "Robert Pattinson returns as the Dark Knight. As Gotham faces a chilling new threat, Bruce Wayne must decide what he's willing to sacrifice for justice.",
    image: "https://image.tmdb.org/t/p/w780/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    releaseDate: "02/10/2026",
    year: 2026,
    duration: "2h 50m",
    rating: 0.0,
    genres: ["Action", "Crime", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
    isUpcoming: true,
  },
  {
    id: 3,
    title: "DUNE: MESSIAH",
    slug: "dune-messiah",
    label: "Warner Bros. Pictures",
    subtitle: "The Desert War Concludes",
    description:
      "Paul Atreides continues his tumultuous reign as Emperor of the known universe, facing cosmic conspiracy and religious zealotry that threatens to tear the imperium apart.",
    image: "https://image.tmdb.org/t/p/w780/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/lzWHmYdfeFiMIY4JaMmtR0GEli3.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    releaseDate: "18/12/2026",
    year: 2026,
    duration: "2h 35m",
    rating: 0.0,
    genres: ["Adventure", "Sci-Fi", "Drama"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isUpcoming: true,
  },
];

export const ALL_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Oppenheimer",
    slug: "oppenheimer",
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    image: "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    year: 2023,
    duration: "3h 0m",
    rating: 8.9,
    genres: ["Biography", "Drama"],
    languages: ["English", "German"],
    quality: "IMAX / 4K",
    pgRating: "R",
  },
  {
    id: 2,
    title: "Dune: Part Two",
    slug: "dune-part-two",
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    image: "https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    year: 2024,
    duration: "2h 46m",
    rating: 8.6,
    genres: ["Sci-Fi", "Action"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
  },
  {
    id: 3,
    title: "Spider-Man: Across the Spider-Verse",
    slug: "spider-man-across-the-spider-verse",
    description:
      "Miles Morales catapults across the Multiverse to battle threats across alternate realities.",
    image: "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    year: 2023,
    duration: "2h 20m",
    rating: 8.7,
    genres: ["Animation", "Action"],
    languages: ["English", "Spanish"],
    quality: "HD / 4K",
    pgRating: "PG",
  },
  {
    id: 4,
    title: "Interstellar",
    slug: "interstellar",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    image: "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    year: 2014,
    duration: "2h 49m",
    rating: 8.7,
    genres: ["Sci-Fi", "Drama"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
  },
  {
    id: 5,
    title: "The Dark Knight",
    slug: "the-dark-knight",
    description:
      "Batman battles the Joker as anarchy and chaos engulf the city of Gotham.",
    image: "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    year: 2008,
    duration: "2h 32m",
    rating: 9.0,
    genres: ["Action", "Crime"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
  },
  {
    id: 6,
    title: "Avengers: Endgame",
    slug: "avengers-endgame",
    description:
      "The Avengers assemble once more in order to reverse Thanos' universe-shattering actions.",
    image: "https://image.tmdb.org/t/p/w780/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    year: 2019,
    duration: "3h 1m",
    rating: 8.4,
    genres: ["Action", "Sci-Fi"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
  },
  {
    id: 7,
    title: "Gladiator II",
    slug: "gladiator-ii",
    description:
      "Lucius enters the Colosseum after his home is conquered by tyrannical Emperors.",
    image: "https://image.tmdb.org/t/p/w780/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    year: 2024,
    duration: "2h 28m",
    rating: 7.3,
    genres: ["Action", "Adventure"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
  },
  {
    id: 8,
    title: "Deadpool & Wolverine",
    slug: "deadpool-and-wolverine",
    description:
      "Deadpool and Wolverine team up to save the timeline in an explosive action adventure.",
    image: "https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    year: 2024,
    duration: "2h 8m",
    rating: 7.7,
    genres: ["Action", "Comedy"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "R",
  },
  {
    id: 9,
    title: "Inception",
    slug: "inception",
    description:
      "A thief who steals secrets through dream technology is given the task of planting an idea.",
    image: "https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    year: 2010,
    duration: "2h 28m",
    rating: 8.8,
    genres: ["Action", "Sci-Fi"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 10,
    title: "Top Gun: Maverick",
    slug: "top-gun-maverick",
    description:
      "Maverick leads TOP GUN's elite graduates on a perilous specialized mission.",
    image: "https://image.tmdb.org/t/p/w780/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    year: 2022,
    duration: "2h 10m",
    rating: 8.3,
    genres: ["Action", "Drama"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
  },
  {
    id: 11,
    title: "The Batman",
    slug: "the-batman",
    description:
      "Batman investigates Gotham City's dark criminal underworld and deep-seated corruption.",
    image: "https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    year: 2022,
    duration: "2h 56m",
    rating: 7.8,
    genres: ["Action", "Crime"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 12,
    title: "Everything Everywhere All at Once",
    slug: "everything-everywhere-all-at-once",
    description:
      "A Chinese-American immigrant is swept up into a mind-bending adventure across the multiverse.",
    image: "https://image.tmdb.org/t/p/w780/w3LxiVYPqrlexP070FFUW5Yv5X1.jpg",
    year: 2022,
    duration: "2h 19m",
    rating: 7.8,
    genres: ["Sci-Fi", "Comedy"],
    languages: ["English", "Mandarin"],
    quality: "HD / 4K",
    pgRating: "R",
  },
  {
    id: 13,
    title: "Black Panther: Wakanda Forever",
    slug: "black-panther-wakanda-forever",
    description:
      "The people of Wakanda fight to protect their homeland from intervening world powers.",
    image: "https://image.tmdb.org/t/p/w780/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    year: 2022,
    duration: "2h 41m",
    rating: 6.7,
    genres: ["Action", "Adventure"],
    languages: ["English", "Spanish"],
    quality: "HD / 4K",
    pgRating: "PG-13",
  },
  {
    id: 14,
    title: "The Godfather",
    slug: "the-godfather",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his empire.",
    image: "https://image.tmdb.org/t/p/w780/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    year: 1972,
    duration: "2h 55m",
    rating: 9.2,
    genres: ["Crime", "Drama"],
    languages: ["English", "Italian"],
    quality: "4K Ultra HD",
    pgRating: "R",
  },
  {
    id: 15,
    title: "Pulp Fiction",
    slug: "pulp-fiction",
    description:
      "The lives of two mob hitmen, a boxer, and a gangster's wife intertwine in Los Angeles.",
    image: "https://image.tmdb.org/t/p/w780/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    year: 1994,
    duration: "2h 34m",
    rating: 8.9,
    genres: ["Crime", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
  },
  {
    id: 16,
    title: "Blade Runner 2049",
    slug: "blade-runner-2049",
    description:
      "A young blade runner unearths a long-buried secret that could plunge society into chaos.",
    image: "https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    year: 2017,
    duration: "2h 44m",
    rating: 8.0,
    genres: ["Sci-Fi", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
  },
  {
    id: 17,
    title: "Peaky Blinders: The Immortal Man",
    slug: "peaky-blinders-the-immortal-man",
    description:
      "Tommy Shelby returns for a feature cinematic continuation of the Birmingham gang empire.",
    image: "https://image.tmdb.org/t/p/w780/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    year: 2025,
    duration: "2h 15m",
    rating: 8.8,
    genres: ["Crime", "Drama"],
    languages: ["English"],
    quality: "4K Ultra HD",
    pgRating: "TV-MA",
  },
  {
    id: 18,
    title: "Extraction 2",
    slug: "extraction-2",
    description:
      "Tyler Rake takes on another high-risk mission to rescue the family of a ruthless gangster.",
    image: "https://image.tmdb.org/t/p/w780/7gKI9hpEMcZUwXrKZrLGOhQI9Pa.jpg",
    year: 2023,
    duration: "2h 3m",
    rating: 7.0,
    genres: ["Action", "Thriller"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
  },
];
