export const seedVideos = [
  {
    videoId: "oppenheimer-trailer",
    title: "Oppenheimer - Official 4K Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
    size: 185,
    runtimeSeconds: 185,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    category: "Trailer",
  },
  {
    videoId: "dune-part-two-trailer",
    title: "Dune: Part Two - Official 4K Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    size: 192,
    runtimeSeconds: 192,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/xOMo8BRK7PfcJv9JCnx7s520b4q.jpg",
    category: "Trailer",
  },
  {
    videoId: "spider-man-spider-verse-trailer",
    title: "Spider-Man: Across the Spider-Verse - Official Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    size: 178,
    runtimeSeconds: 178,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    category: "Trailer",
  },
  {
    videoId: "deadpool-and-wolverine-trailer",
    title: "Marvel Studios' Deadpool & Wolverine - Official Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=73_1biulkYk",
    size: 158,
    runtimeSeconds: 158,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg",
    category: "Trailer",
  },
  {
    videoId: "gladiator-ii-trailer",
    title: "Gladiator II - Official 4K Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=4rgYUipGJNo",
    size: 180,
    runtimeSeconds: 180,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/euYIwmwkmz95mnXvufEmbL6ovhA.jpg",
    category: "Trailer",
  },
  {
    videoId: "avengers-endgame-trailer",
    title: "Marvel Studios' Avengers: Endgame - Official Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    size: 146,
    runtimeSeconds: 146,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    category: "Trailer",
  },
  {
    videoId: "interstellar-trailer",
    title: "Interstellar - Official Theatrical Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    size: 152,
    runtimeSeconds: 152,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/rAiYTsqOdAc0VAlxAqAe0qZ9nuk.jpg",
    category: "Trailer",
  },
  {
    videoId: "the-dark-knight-trailer",
    title: "The Dark Knight - Official Trailer",
    provider: "YouTube",
    videoUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    size: 140,
    runtimeSeconds: 140,
    thumbnailUrl: "https://image.tmdb.org/t/p/w780/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    category: "Trailer",
  },
];

export const seedActors = [
  {
    slug: "denzel-washington",
    name: "Denzel Washington",
    role: "American Actor & Filmmaker",
    label: "Featured Talent",
    shortDesc: "A multi-Academy Award winning titan of modern cinema, renowned for iconic performances in 'Training Day', 'Fences', and 'Gladiator II'.",
    bio: [
      "Denzel Hayes Washington Jr. is an American actor, producer, and director. In a career spanning over four decades, Washington has received numerous accolades, including two Academy Awards, a Tony Award, and three Golden Globe Awards.",
      "He is widely regarded as one of the greatest actors of his generation, known for his ability to embody complex characters with dignity, immense gravity, and intense emotional depth.",
    ],
    details: {
      born: "December 28, 1954 • Mount Vernon, NY",
      awards: "2 Academy Awards, 3 Golden Globes, 1 Tony",
      training: "Fordham University, American Conservatory Theater",
    },
    image: "/assets/images/Denzel.png",
    isFeatured: true,
  },
  {
    slug: "angelina-jolie",
    name: "Angelina Jolie",
    role: "American Actress & Director",
    label: "Featured Talent",
    shortDesc: "Academy Award-winning actress celebrated for versatile cinematic roles ranging from 'Girl, Interrupted' to 'Maleficent' and 'Maria'.",
    bio: [
      "Angelina Jolie is an American actress, filmmaker, and humanitarian. The recipient of numerous accolades, including an Academy Award and three Golden Globe Awards, she has been named Hollywood's highest-paid actress multiple times.",
      "Beyond her cinematic achievements, she is noted for her extensive humanitarian efforts, for which she has received a Jean Hersholt Humanitarian Award.",
    ],
    details: {
      born: "June 4, 1975 • Los Angeles, CA",
      awards: "1 Academy Award, 3 Golden Globes, 2 SAG Awards",
      training: "Lee Strasberg Theatre and Film Institute",
    },
    image: "/assets/images/Angelina.png",
    isFeatured: true,
  },
  {
    slug: "tom-hanks",
    name: "Tom Hanks",
    role: "American Actor & Producer",
    label: "Featured Talent",
    shortDesc: "Beloved worldwide for legendary roles in 'Forrest Gump', 'Cast Away', 'Saving Private Ryan', and 'Apollo 13'.",
    bio: [
      "Thomas Jeffrey Hanks is an American actor and filmmaker. Known for both his comedic and dramatic roles, he is one of the most popular and recognizable film stars worldwide.",
      "Hanks is the recipient of several honors, including back-to-back Academy Awards for Best Actor, the Presidential Medal of Freedom, and the Cecil B. DeMille Award.",
    ],
    details: {
      born: "July 9, 1956 • Concord, CA",
      awards: "2 Academy Awards, 4 Golden Globes, 7 Emmy Awards",
      training: "California State University, Sacramento",
    },
    image: "/assets/images/tom-hanks.jpg",
    isFeatured: true,
  },
  {
    slug: "jennifer-aniston",
    name: "Jennifer Aniston",
    role: "American Actress & Producer",
    label: "Featured Talent",
    shortDesc: "Emmy and Golden Globe winner celebrated for 'Friends', 'The Morning Show', and a successful roster of acclaimed feature films.",
    bio: [
      "Jennifer Joanna Aniston rose to international fame for her role as Rachel Green on the television sitcom Friends, for which she earned Primetime Emmy, Golden Globe, and Screen Actors Guild awards.",
      "She continues to captivate global audiences with critically acclaimed dramatic roles including her lead performance in Apple TV's The Morning Show.",
    ],
    details: {
      born: "February 11, 1969 • Los Angeles, CA",
      awards: "1 Emmy Award, 1 Golden Globe, 1 SAG Award",
      training: "Fiorello H. LaGuardia High School of Music & Art",
    },
    image: "/assets/images/Jennifer.png",
    isFeatured: true,
  },
  {
    slug: "al-pacino",
    name: "Al Pacino",
    role: "American Actor & Filmmaker",
    label: "Featured Talent",
    shortDesc: "Cinematic icon famed for 'The Godfather' trilogy, 'Scarface', 'Heat', and 'Scent of a Woman'. Triple Crown of Acting recipient.",
    bio: [
      "Alfredo James Pacino is an American actor. Considered one of the most influential actors of the 20th century, he has received numerous accolades including an Academy Award, two Tony Awards, and two Primetime Emmy Awards.",
      "His career has spanned over five decades, and he remains one of the few performers to have achieved the 'Triple Crown of Acting' in the United States.",
    ],
    details: {
      born: "April 25, 1940 • New York City, NY",
      awards: "1 Academy Award, 2 Tonys, 2 Emmys, 4 Golden Globes",
      training: "HB Studio, The Actors Studio",
    },
    image: "/assets/images/Pacino.png",
    isFeatured: true,
  },
  {
    slug: "cillian-murphy",
    name: "Cillian Murphy",
    role: "Irish Actor",
    label: "Featured Talent",
    shortDesc: "Academy Award winner for 'Oppenheimer' and world-renowned as Thomas Shelby in the global cultural sensation 'Peaky Blinders'.",
    bio: [
      "Cillian Murphy is an Irish actor who achieved international acclaim for his collaborations with director Christopher Nolan and his role as Tommy Shelby.",
      "In 2024, Murphy won the Academy Award for Best Actor for his commanding titular performance in Oppenheimer.",
    ],
    details: {
      born: "May 25, 1976 • Douglas, Cork, Ireland",
      awards: "1 Academy Award, 1 BAFTA, 1 Golden Globe, 1 SAG Award",
      training: "Corcadorca Theatre Company, UCC",
    },
    image: "/assets/images/cillian-murphy.jpg",
    isFeatured: true,
  },
  {
    slug: "zendaya",
    name: "Zendaya",
    role: "American Actress & Singer",
    label: "Featured Talent",
    shortDesc: "Two-time Emmy Award winner recognized for leading roles in 'Dune: Part One & Two', 'Euphoria', 'Challengers', and 'Spider-Man'.",
    bio: [
      "Zendaya Maree Stoermer Coleman is an American actress and singer who has received multiple accolades including two Primetime Emmy Awards and a Golden Globe Award.",
      "She has established herself as one of the most prominent leading actors in global cinema with box office sensations such as Dune and Challengers.",
    ],
    details: {
      born: "September 1, 1996 • Oakland, CA",
      awards: "2 Primetime Emmy Awards, 1 Golden Globe",
      training: "American Conservatory Theater, Oakland School for the Arts",
    },
    image: "/assets/images/zendaya.jpg",
    isFeatured: true,
  },
  {
    slug: "leonardo-dicaprio",
    name: "Leonardo DiCaprio",
    role: "American Actor & Producer",
    label: "Featured Talent",
    shortDesc: "Academy Award winner celebrated for masterpieces including 'Inception', 'Titanic', 'The Wolf of Wall Street', and 'The Revenant'.",
    bio: [
      "Leonardo Wilhelm DiCaprio is an American actor and film producer. Known for his work in biopics and period films, he has received numerous accolades, including an Academy Award, a British Academy Film Award, and three Golden Globe Awards.",
      "His films have grossed over $7.2 billion worldwide, placing him among the highest-earning actors in cinema history.",
    ],
    details: {
      born: "November 11, 1974 • Los Angeles, CA",
      awards: "1 Academy Award, 1 BAFTA, 3 Golden Globes",
      training: "Los Angeles Center for Enriched Studies",
    },
    image: "/assets/images/leonardo-dicaprio.jpg",
    isFeatured: true,
  },
];

export const seedMovies = [
  {
    title: "Oppenheimer",
    slug: "oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    image: "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
    year: 2023,
    duration: "3h 0m",
    rating: 8.9,
    genres: ["Biography", "Drama", "History"],
    languages: ["English", "German", "Dutch"],
    quality: "IMAX / 4K",
    pgRating: "R",
    isFeatured: true,
    isUpcoming: false,
    isTrending: true,
    label: "Universal Pictures",
    subtitle: "The World Forever Changes",
    releaseDate: "21/07/2023",
  },
  {
    title: "Dune: Part Two",
    slug: "dune-part-two",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    image: "https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520b4q.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    year: 2024,
    duration: "2h 46m",
    rating: 8.6,
    genres: ["Sci-Fi", "Adventure", "Action"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isFeatured: true,
    isUpcoming: false,
    isTrending: true,
    label: "Warner Bros. Pictures",
    subtitle: "Long Live the Fighters",
    releaseDate: "01/03/2024",
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    slug: "spider-man-across-the-spider-verse",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    image: "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    year: 2023,
    duration: "2h 20m",
    rating: 8.7,
    genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
    languages: ["English", "Spanish"],
    quality: "HD / 4K",
    pgRating: "PG",
    isFeatured: true,
    isUpcoming: false,
    isTrending: true,
    label: "Sony Pictures Animation",
    subtitle: "It's How You Wear the Mask",
    releaseDate: "02/06/2023",
  },
  {
    title: "Interstellar",
    slug: "interstellar",
    description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft along with a team of researchers to find a new planet for humans.",
    image: "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rAiYTsqOdAc0VAlxAqAe0qZ9nuk.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    year: 2014,
    duration: "2h 49m",
    rating: 8.7,
    genres: ["Sci-Fi", "Drama", "Adventure"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isFeatured: true,
    isUpcoming: false,
    isTrending: true,
    label: "Paramount Pictures",
    subtitle: "Mankind Was Born on Earth. It Was Never Meant to Die Here.",
    releaseDate: "07/11/2014",
  },
  {
    title: "The Dark Knight",
    slug: "the-dark-knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    image: "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    year: 2008,
    duration: "2h 32m",
    rating: 9.0,
    genres: ["Action", "Crime", "Drama"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isFeatured: true,
    isUpcoming: false,
    isTrending: true,
    label: "Warner Bros.",
    subtitle: "Why So Serious?",
    releaseDate: "18/07/2008",
  },
  {
    title: "Avengers: Endgame",
    slug: "avengers-endgame",
    description: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions.",
    image: "https://image.tmdb.org/t/p/w780/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    year: 2019,
    duration: "3h 1m",
    rating: 8.4,
    genres: ["Action", "Sci-Fi", "Adventure"],
    languages: ["English", "Japanese"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isFeatured: true,
    isUpcoming: false,
    isTrending: true,
    label: "Marvel Studios",
    subtitle: "Part of the Journey is the End",
    releaseDate: "26/04/2019",
  },
  {
    title: "Gladiator II",
    slug: "gladiator-ii",
    description: "Years after witnessing the death of the revered hero Maximus, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist.",
    image: "https://image.tmdb.org/t/p/w780/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhA.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=4rgYUipGJNo",
    year: 2024,
    duration: "2h 28m",
    rating: 7.3,
    genres: ["Action", "Adventure", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: false,
    isTrending: true,
    label: "Paramount Pictures",
    subtitle: "What We Do in Life Echoes in Eternity",
    releaseDate: "22/11/2024",
  },
  {
    title: "Deadpool & Wolverine",
    slug: "deadpool-and-wolverine",
    description: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary Deadpool behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit up again with Wolverine.",
    image: "https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=73_1biulkYk",
    year: 2024,
    duration: "2h 8m",
    rating: 7.7,
    genres: ["Action", "Comedy", "Sci-Fi"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "R",
    isFeatured: true,
    isUpcoming: false,
    isTrending: true,
    label: "Marvel Studios",
    subtitle: "Everyone Deserves a Happy Ending",
    releaseDate: "26/07/2024",
  },
  {
    title: "Inception",
    slug: "inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    image: "https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    year: 2010,
    duration: "2h 28m",
    rating: 8.8,
    genres: ["Action", "Sci-Fi", "Adventure"],
    languages: ["English", "Japanese", "French"],
    quality: "HD / 4K",
    pgRating: "PG-13",
    isFeatured: false,
    isUpcoming: false,
    isTrending: true,
    label: "Warner Bros.",
    subtitle: "Your Mind is the Scene of the Crime",
    releaseDate: "16/07/2010",
  },
  {
    title: "Top Gun: Maverick",
    slug: "top-gun-maverick",
    description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on an impossible mission.",
    image: "https://image.tmdb.org/t/p/w780/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=giXco2jaZ_4",
    year: 2022,
    duration: "2h 10m",
    rating: 8.3,
    genres: ["Action", "Drama"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isFeatured: false,
    isUpcoming: false,
    isTrending: true,
    label: "Paramount Pictures",
    subtitle: "Feel the Need for Speed",
    releaseDate: "27/05/2022",
  },
  {
    title: "The Batman",
    slug: "the-batman",
    description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    image: "https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/tRS6jvPM9qPrrnx2KRx3ew96Yot.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    year: 2022,
    duration: "2h 56m",
    rating: 7.8,
    genres: ["Action", "Crime", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
    isFeatured: false,
    isUpcoming: false,
    isTrending: true,
    label: "DC Films / Warner Bros.",
    subtitle: "Unmask the Truth",
    releaseDate: "04/03/2022",
  },
  {
    title: "Everything Everywhere All at Once",
    slug: "everything-everywhere-all-at-once",
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    image: "https://image.tmdb.org/t/p/w780/w3LxiVYPqrlexP070FFUW5Yv5X1.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/8YFL5QQVPy3AgrEQxNYvsgiPEbe.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=wxN1T1ux194",
    year: 2022,
    duration: "2h 19m",
    rating: 7.8,
    genres: ["Sci-Fi", "Comedy", "Action"],
    languages: ["English", "Mandarin", "Cantonese"],
    quality: "HD / 4K",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: false,
    isTrending: false,
    label: "A24",
    subtitle: "The Universe is So Much Bigger Than You Realize",
    releaseDate: "25/03/2022",
  },
  {
    title: "Black Panther: Wakanda Forever",
    slug: "black-panther-wakanda-forever",
    description: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    image: "https://image.tmdb.org/t/p/w780/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=_Z3QKkl1WyM",
    year: 2022,
    duration: "2h 41m",
    rating: 6.7,
    genres: ["Action", "Adventure", "Drama"],
    languages: ["English", "Spanish", "Xhosa"],
    quality: "HD / 4K",
    pgRating: "PG-13",
    isFeatured: true,
    isUpcoming: false,
    isTrending: false,
    label: "Marvel Studios",
    subtitle: "Forever",
    releaseDate: "11/11/2022",
  },
  {
    title: "The Godfather",
    slug: "the-godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    image: "https://image.tmdb.org/t/p/w780/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWF92Q2viGbhZzgFx.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=sY1S34973zA",
    year: 1972,
    duration: "2h 55m",
    rating: 9.2,
    genres: ["Crime", "Drama"],
    languages: ["English", "Italian"],
    quality: "4K Ultra HD",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: false,
    isTrending: true,
    label: "Paramount Pictures",
    subtitle: "An Offer You Can't Refuse",
    releaseDate: "24/03/1972",
  },
  {
    title: "Pulp Fiction",
    slug: "pulp-fiction",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    image: "https://image.tmdb.org/t/p/w780/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
    year: 1994,
    duration: "2h 34m",
    rating: 8.9,
    genres: ["Crime", "Drama"],
    languages: ["English", "Spanish", "French"],
    quality: "HD / 4K",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: false,
    isTrending: false,
    label: "Miramax",
    subtitle: "Girls like me don't make invitations like this every day.",
    releaseDate: "14/10/1994",
  },
  {
    title: "Blade Runner 2049",
    slug: "blade-runner-2049",
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    image: "https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlxGq.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=gCcx85zbxz4",
    year: 2017,
    duration: "2h 44m",
    rating: 8.0,
    genres: ["Sci-Fi", "Mystery", "Drama"],
    languages: ["English", "Japanese", "Russian"],
    quality: "HD / 4K",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: false,
    isTrending: false,
    label: "Warner Bros.",
    subtitle: "The Key to the Future is Finally Unearthed",
    releaseDate: "06/10/2017",
  },
  {
    title: "AVENGERS: DOOMSDAY",
    slug: "avengers-doomsday",
    description: "A new era of the MCU begins as Doctor Doom rises to reshape reality. The remaining heroes must unite for the ultimate stand against cosmic destruction.",
    image: "https://image.tmdb.org/t/p/w780/mQZxtvA6p2dE79D0fR0iYIq57Qe.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    year: 2026,
    duration: "2h 45m",
    rating: 0.0,
    genres: ["Action", "Sci-Fi", "Adventure"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isFeatured: false,
    isUpcoming: true,
    isTrending: false,
    label: "Marvel Studios",
    subtitle: "The Multiverse Collapses",
    releaseDate: "01/05/2026",
  },
  {
    title: "THE BATMAN PART II",
    slug: "the-batman-part-ii",
    description: "Robert Pattinson returns as the Dark Knight. As Gotham faces a chilling new threat, Bruce Wayne must decide what he's willing to sacrifice for justice.",
    image: "https://image.tmdb.org/t/p/w780/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    year: 2026,
    duration: "2h 50m",
    rating: 0.0,
    genres: ["Action", "Crime", "Drama"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: true,
    isTrending: false,
    label: "DC Studios",
    subtitle: "Deep in the Shadows",
    releaseDate: "02/10/2026",
  },
  {
    title: "DUNE: MESSIAH",
    slug: "dune-messiah",
    description: "Paul Atreides continues his tumultuous reign as Emperor of the known universe, facing cosmic conspiracy and religious zealotry that threatens to tear the imperium apart.",
    image: "https://image.tmdb.org/t/p/w780/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/lzWHmYdfeFiMIY4JaMmtR0GEli3.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    year: 2026,
    duration: "2h 35m",
    rating: 0.0,
    genres: ["Adventure", "Sci-Fi", "Drama"],
    languages: ["English"],
    quality: "IMAX / 4K",
    pgRating: "PG-13",
    isFeatured: false,
    isUpcoming: true,
    isTrending: false,
    label: "Warner Bros. Pictures",
    subtitle: "The Desert War Concludes",
    releaseDate: "18/12/2026",
  },
  {
    title: "Peaky Blinders: The Immortal Man",
    slug: "peaky-blinders-the-immortal-man",
    description: "Tommy Shelby returns for a feature-length cinematic continuation of the Birmingham gang empire during World War II.",
    image: "https://image.tmdb.org/t/p/w780/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/w7aTfK4VeqyZ7p3P6nLd92L1pEa.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=2nsT9uQPIrk",
    year: 2025,
    duration: "2h 15m",
    rating: 8.8,
    genres: ["Crime", "Drama", "Action"],
    languages: ["English", "Romani"],
    quality: "4K Ultra HD",
    pgRating: "TV-MA",
    isFeatured: false,
    isUpcoming: false,
    isTrending: true,
    label: "BBC / Netflix",
    subtitle: "By Order of the Peaky Blinders",
    releaseDate: "15/09/2025",
  },
  {
    title: "Extraction 2",
    slug: "extraction-2",
    description: "Back from the brink of death, highly skilled commando Tyler Rake takes on another dangerous mission: saving the imprisoned family of a ruthless gangster.",
    image: "https://image.tmdb.org/t/p/w780/7gKI9hpEMcZUwXrKZrLGOhQI9Pa.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/9n2tJBplPbgR2ca05h6qL8iqupS.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=Y274jZs5s7s",
    year: 2023,
    duration: "2h 3m",
    rating: 7.0,
    genres: ["Action", "Thriller"],
    languages: ["English", "Georgian"],
    quality: "HD / 4K",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: false,
    isTrending: false,
    label: "Netflix",
    subtitle: "You Only Get One Shot at a Second Chance",
    releaseDate: "16/06/2023",
  },
  {
    title: "The Irishman",
    slug: "the-irishman",
    description: "Hitman Frank Sheeran looks back at the secrets he kept as a loyal member of the Bufalino crime family in this acclaimed Martin Scorsese epic.",
    image: "https://image.tmdb.org/t/p/w780/mbm8k3GFbhRegVqgm7L9cnbtCmg.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/scNcjE3N8RfvU0P6J9G0eM3N9s4.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=WHXxVmeGQUc",
    year: 2019,
    duration: "3h 29m",
    rating: 7.8,
    genres: ["Biography", "Crime", "Drama"],
    languages: ["English", "Italian"],
    quality: "4K Ultra HD",
    pgRating: "R",
    isFeatured: false,
    isUpcoming: false,
    isTrending: false,
    label: "Tribeca Productions / Netflix",
    subtitle: "I Heard You Paint Houses",
    releaseDate: "27/11/2019",
  },
  {
    title: "Doctor Strange in the Multiverse of Madness",
    slug: "doctor-strange-in-the-multiverse-of-madness",
    description: "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses to battle multiple threats.",
    image: "https://image.tmdb.org/t/p/w780/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=aWzlQ2N6qqg",
    year: 2022,
    duration: "2h 6m",
    rating: 6.9,
    genres: ["Action", "Adventure", "Fantasy"],
    languages: ["English", "Spanish"],
    quality: "HD / 4K",
    pgRating: "PG-13",
    isFeatured: false,
    isUpcoming: false,
    isTrending: false,
    label: "Marvel Studios",
    subtitle: "Enter a New Dimension of Strange",
    releaseDate: "06/05/2022",
  },
  {
    title: "Jumanji: The Next Level",
    slug: "jumanji-the-next-level",
    description: "The gang is back but the game has changed. As they return to rescue one of their own, they discover that nothing is as they expect.",
    image: "https://image.tmdb.org/t/p/w780/jyw8VKYEiM1UDzPB77gaAGJ3Lo9.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/zTxHf9iIOCqRbyPx7tgyqOc2NWb.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=rBxcF-r9Ibs",
    year: 2019,
    duration: "2h 3m",
    rating: 6.7,
    genres: ["Action", "Adventure", "Comedy"],
    languages: ["English"],
    quality: "HD / 4K",
    pgRating: "PG-13",
    isFeatured: false,
    isUpcoming: false,
    isTrending: false,
    label: "Sony Pictures",
    subtitle: "Play Again",
    releaseDate: "13/12/2019",
  },
];
